pub mod kline;

pub enum Spot {
    Ping,
    Time,
    ExchangeInfo,
    Depth,
    Trades,
    HistoricalTrades,
    AggTrades,
    /// interval: 1s 1m 3m 5m 15m 30m 1h 2h 4h 6h 8h 12h 1d 3d 1w 1M
    Klines,
    AvgPrice,
    UiKlines,
    Ticker24hr,
    TickerPrice,
    TickerBookTicker,
    Ticker,
    OrderTest,
    Order,
    OpenOrders,
    OrderCancelReplace,
    AllOrders,
    OrderOco,
    OrderList,
    AllOrderList,
    OpenOrderList,
    Account,
    MyTrades,
    RateLimitOrder,
    UserDataStream,
}
